### ISSUE TITLE
URLs open in new window rather than tab

### ISSUE THREAD

**Issue by fishter** [DanTup/BrowserSelector#1]
This is on ie9 with Chrome set as the first browser.
URLs that match my ie rules open in new windows. I'll check the reuse windows option when I get my windows machine out again.

**Comment by fishter** [comment]
**Options in IE9**

Reuse windows is checked
- [x] Reuse windows for launching shortcuts (when tabbed browsing is off)

The *Open links from other programs in:* option is
- [x] A new tab in the current window

**Comment by DanTup** [comment]
Thanks for checking; I'll investigate when I get some time. I'm surprised it doesn't just work by default like Chrome - I'd expect the process to spot there's another IE window open, and pass the url on to that :(

**Comment by fishter** [comment]
maybe -framemerging or -sessionmerging options on command line will have an effect?
#longshot!!

**Comment by DanTup** [comment]
hmmm, this is strange... If I run this twice from a console, it opens new windows:

    "C:\Program Files\Internet Explorer\iexplore.exe" "http://www.microsoft.com/"

However, if I do:

    start "http://www.microsoft.com/"

Then it opens in two tabs in the same window (assuming IE default browser). However, in the registry at CLASSES\IE.HTTP\shell\open\command it has:

    "C:\Program Files\Internet Explorer\iexplore.exe" %1

There just be something special causing it not to use that exact command when it's the default browser...

**Comment by DanTup** [comment]
Posted to SO, to see if anyone has any ideas: http://stackoverflow.com/q/32722443/25124

**Comment by fishter** [comment]
It's not such a huge deal - the child windows can easily be docked manually.
Thanks for exposing the fact that Microsoft do special things that other browsers don't.  But that's hardly a secret.

**Comment by tacarrie** [comment]
The issue has been closed but without a solution. Is there really no way that BrowserSelector could handle that?

**Comment by DanTup** [comment]
@tacarrie see my comment above and the linked StackOverflow question. Apparently this trivial task is not so trivial 😞

As mentioned in the readme, I'm not actively maintaining this any more, so if you need changes you may need to make them (or see if someone has already made them on a fork).

**Comment by tacarrie** [comment]
@DanTup I checked all the forks and most of them are either behind your master branch or even. The few ones that are ahead did not implement anything in this direction. :(
It's sad to see that such a great utility is not further developed. However, thank you for what you have done so far!
