### ISSUE TITLE
Unable open file:///C:/TEMP/xxx.html URL

### ISSUE THREAD

**Issue by doggy8088** [DanTup/BrowserSelector#16]
BrowserSelector can't open local file with `file:///C:/TEMP/xxx.html` URI.

**Comment by doggy8088** [comment]
@DanTup Will you release a new version after this merge?

**Comment by DanTup** [comment]
This project is no longer being maintained. I'll still merge PRs that look sensible, but I'm not making releases (I mostly use macOS now and don't have easy access to Visual Studio). If you want an updated build, you'll have to build it yourself.
