### ISSUE TITLE
text box for CURL command

### ISSUE THREAD

**Issue by est** [DanTup/BrowserSelector#2]
Provide a text box where you can copy the URL as CURL command for easy pasting into a shell 

thanks!

**Comment by DanTup** [comment]
This is somewhat out of scope for this tool, it's really only designed to proxy commands to other applications and this request is really specific.

That said, if you created a little app that takes a url as a parameter and pops open the text box as you wish, you could use this tool to pass commands to it (though I must admit, I don't fully understand the use case you have).
