### ISSUE TITLE
Crash when unregister

### ISSUE THREAD

**Issue by AngelM1981** [DanTup/BrowserSelector#6]
Run:

`BrowserSelector.exe --unregister`

under Windows 7 and BrowserSelctor will crash.

**Comment by DanTup** [comment]
Are you able to provide an error message or stack trace? It should be visible in Event Viewer if you don't already see it spat out on the screen,

**Comment by AngelM1981** [comment]
Sorry I disabled it already and deleted it. Sinne it des not Work for me.

Danny Tuppeny <notifications@github.com> schrieb am Mo., 22. Feb. 2016
15:19:

**Comment by DanTup** [comment]
I don't have easy access to Windows 7; if anyone else can repro this and provide an error message or more info, I'll investigate.
